apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/managed-by: kustomize
  name: gateway-editor-role
rules:
- apiGroups: [gateway.orka.ai]
  resources: [gateways, gatewaybindings]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [gateway.orka.ai]
  resources: [gateways/status, gatewaybindings/status]
  verbs: [get]
- apiGroups: [gateway.orka.ai]
  resources: [gatewayevents, gatewaydeliveries]
  verbs: [get, list]
- apiGroups: [gateway.orka.ai]
  resources: [gatewaydeliveries]
  verbs: [update]
