# This rule is not used by the project orka itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the core.orka.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/managed-by: kustomize
  name: task-editor-role
rules:
- apiGroups:
  - core.orka.ai
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.orka.ai
  resources:
  - tasks/status
  verbs:
  - get
- apiGroups:
  - core.orka.ai
  resources:
  - sessions
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - core.orka.ai
  resources:
  - tasks/approvals
  verbs:
  - update
