/*
Copyright (c) 2026.

MIT License - see LICENSE file for details.
*/

package tools

// Test-only fixture constants shared across this package's tests.
const (
	shortPollIntervalString        = "100ms"
	taskPhaseRunningString         = "Running"
	taskPhaseSucceededString       = "Succeeded"
	taskPhaseFailedString          = "Failed"
	testToolDescription            = "A test tool"
	httpMethodGetString            = "GET"
	testRepositoryName             = "ayna"
	testPullRequestTitle           = "Test PR"
	testAgentTaskGeneratedName     = "agent-task-1"
	testContainerTaskGeneratedName = "container-task-1"
	testCoderTaskName              = "coder-task"
	testChildTaskName              = "child-task-1"
	testCoordinatorTaskName        = "coordinator"
	testCoderAgentName             = "coder"
	testClaudeCoderName            = "claude-coder"
	runtimeTypeClaude              = "claude"
	testSecondToolDescription      = "Second tool"
	testTool1Description           = "Tool 1"
	testCustomCopilotSecretName    = "custom-copilot-secret"
	testCustomNamespaceCaseName    = "custom namespace"
	failedToParseArgumentsMessage  = "failed to parse arguments"
	resultField                    = "result"
	providerOpenAI                 = "openai"
	managedByLabelValue            = "orka.ai/managed"
	testGitCredsSecretName         = "git-creds"
	testSozercanAynaRepoURL        = "https://github.com/sozercan/ayna"
	testOrgTestRepoURL             = "https://github.com/testorg/testrepo"
	testNamespace                  = "test-ns"
	testMyToolName                 = "my-tool"
	testNonexistentName            = "nonexistent"
	testMyTaskName                 = "my-task"
	testResearcherAgentName        = "researcher"
	testGitHubOwner                = "sozercan"
	testWorkerAName                = "worker-a"
	testMyAgentName                = "my-agent"
	testTool1Name                  = "tool1"
	testOrgRepoURL                 = "https://github.com/org/repo"
	testRuntimeCredsSecretName     = "runtime-creds"
	testTaskBName                  = "task-b"
	testToolName                   = "test_tool"
	testProdNamespace              = "prod"
	testFeatureBranch              = "feature/x"
	testTaskAName                  = "task-a"
	testAgentName                  = "test-agent"
	testHelloText                  = "hello"
	exampleDotComURL               = "http://example.com"
	exampleAPIURL                  = "http://example.com/api"
	localhostURL                   = "http://localhost"
	testMyOrgRepoURL               = "https://github.com/myorg/myrepo"
	otherSecretKey                 = "other-key"
	testReviewBody                 = "review"
	testSiblingTaskName            = "sibling-1"
	testTaskOKName                 = "task-ok"
	testTool2Name                  = "tool2"
	testEditCommitTitle            = "feat: edit message"
	testEditMessageBranch          = "feature/edit-msg"
	testGPT4OModel                 = "gpt-4o"
	helloOutputString              = "hello\n"
	testNoWorkspaceTaskName        = "no-ws-task"
	testPriorTaskName              = "prior-task-1"
	testRunningTaskName            = "running-task"
	testSessionID                  = "sess-123"
	testCommentBody                = "some comment"
	testTaskFailName               = "task-fail"
	testTaskPendingName            = "task-pending"
	testPlanJSON                   = `{"summary":"test","plan_document":"# Plan"}`
	invalidJSONText                = "{invalid}"
	testGitHubToken                = "test-token"
	invalidJSONArgsCaseName        = "invalid JSON args"
	serverErrorMessage             = "server error"
	invalidArgumentsMessage        = "invalid arguments"
	missingNameCaseName            = "missing name"
	taskNotFoundCaseName           = "task not found"
	invalidTimeoutCaseName         = "invalid timeout"
	k8sAlreadyExistsErrorCaseName  = "k8s already exists error"
	notFoundMessage                = "not found"
)
