#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/generate-cli-docs.sh [--check] [output-file]

Generate the Docusaurus CLI command reference from the compiled orka binary.

The command list is discovered by walking the cobra command tree from
`orka --help`, so a new command appears in the docs as soon as it is
registered. Nothing here is hardcoded.

Set ORKA_CLI_BIN to use a specific binary. Defaults to bin/orka and builds it
with make build-cli when it is missing.
USAGE
}

check=false
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi
if [[ "${1:-}" == "--check" ]]; then
  check=true
  shift
fi

out="${1:-website/docs/reference/cli-commands.md}"
cli_bin="${ORKA_CLI_BIN:-bin/orka}"

if [[ ! -x "$cli_bin" ]]; then
  make build-cli >/dev/null
fi

# Commands whose subcommands are cobra boilerplate rather than Orka surface.
# The parent is still documented; only the recursion stops.
no_recurse=" completion "

# List the direct subcommands of one command path. Cobra prints them in a
# section whose heading ends in "Commands:" ("Available Commands:", or one
# heading per group when command groups are used) and ends at the next blank
# line.
list_children() {
  local path="$1"
  # shellcheck disable=SC2206
  local parts=($path)
  "$cli_bin" ${parts[@]+"${parts[@]}"} --help 2>/dev/null | awk '
    /Commands:[[:space:]]*$/ { in_section = 1; next }
    /^[[:space:]]*$/         { in_section = 0 }
    in_section && /^[[:space:]]+[a-zA-Z0-9]/ { print $1 }
  '
}

# Depth-first walk, parent before children, in the order cobra lists them.
walk() {
  local path="$1"
  printf '%s\n' "$path"

  if [[ -n "$path" && "$no_recurse" == *" ${path##* } "* ]]; then
    return 0
  fi

  local children
  children="$(list_children "$path")"
  local child
  for child in $children; do
    # `help` is generated by cobra for every command and documents itself.
    [[ "$child" == "help" ]] && continue
    if [[ -z "$path" ]]; then
      walk "$child"
    else
      walk "$path $child"
    fi
  done
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# Complete discovery before reading its output so help failures abort the script.
walk "" > "$tmp"

commands=()
while IFS= read -r command; do
  commands+=("$command")
done < "$tmp"

if [[ "${#commands[@]}" -lt 2 ]]; then
  echo "no subcommands discovered from $cli_bin --help; is the binary current?" >&2
  exit 1
fi

{
  cat <<'HEADER'
---
slug: /cli-commands
description: "Generated help output for every orka CLI command."
---

# CLI command reference

This page is generated from `orka --help` output. Do not edit it by hand; run:

```bash
make docs-cli
```

For workflow-oriented examples and coverage notes, see [CLI reference](./cli.md).

HEADER

  for command in "${commands[@]}"; do
    if [[ -z "$command" ]]; then
      title="orka"
      args=(--help)
    else
      title="orka $command"
      # shellcheck disable=SC2206
      parts=($command)
      args=("${parts[@]}" --help)
    fi

    printf '## `%s`\n\n' "$title"
    printf '```text\n'
    "$cli_bin" "${args[@]}"
    printf '```\n\n'
  done
} > "$tmp"

if [[ "$check" == true ]]; then
  if ! cmp -s "$tmp" "$out"; then
    echo "$out is out of date; run make docs-cli" >&2
    diff -u "$out" "$tmp" >&2 || true
    exit 1
  fi
  echo "$out is up to date"
else
  mkdir -p "$(dirname "$out")"
  mv "$tmp" "$out"
  trap - EXIT
fi
